

services:
  transcode:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    restart: unless-stopped
    volumes:
      - type: bind
        source: .
        target: /usr/src/app/
    ports:
      - 3000:3000